// Video Scheduler Types

// YouTube Video Settings - Complete Feature Set (2024)
export interface YouTubeVideoSettings {
    // Basic Details
    title: string; // Max 100 characters
    description: string; // Max 5000 characters
    
    // Tags & Hashtags
    tags: string[]; // Max 500 characters total
    hashtags: string[]; // Max 15 hashtags, first 3 appear above title
    
    // Classification
    categoryId: string;
    playlistIds: string[]; // Add to playlists
    
    // Visibility
    privacyStatus: 'private' | 'public' | 'unlisted';
    scheduledTime?: string; // ISO date string
    scheduleTimezone?: string; // Timezone for scheduling
    isPremiere: boolean; // For scheduled public videos
    
    // Premiere Settings
    premiereCountdownTheme?: 'default' | 'alternative' | 'dramatic' | 'ambient';
    premiereTrailerVideoId?: string; // Trailer to play before premiere
    premiereEnableLiveChat?: boolean;
    premiereLiveRedirectEnabled?: boolean; // Redirect to live stream after
    premiereLiveRedirectVideoId?: string;
    
    // Audience
    madeForKids: 'yes' | 'no' | 'unset';
    ageRestriction: boolean; // 18+ content
    
    // Paid Promotion
    hasPaidPromotion: boolean;
    
    // Comments & Ratings
    commentsMode: 'all' | 'approved' | 'none' | 'moderated';
    sortCommentsBy: 'top' | 'newest';
    showRatings: boolean; // Show likes
    firstComment?: string; // Creator first comment (pinned)
    
    // Distribution
    allowEmbedding: boolean;
    publishToFeed: boolean; // Publish to subscriptions feed
    allowSearching: boolean; // Allow in YouTube search
    
    // Clips & Remix
    allowClips: boolean; // Allow viewers to create clips
    allowRemix: boolean; // Allow content to be remixed in Shorts
    
    // AI & Altered Content
    allowAITraining: boolean; // Allow video to train YouTube's AI
    isAIGenerated: boolean; // Mark as AI-generated content
    hasAlteredContent: boolean; // Contains realistic altered/synthetic content
    alteredContentDescription?: string; // Description of what's altered
    
    // License
    license: 'youtube' | 'creativeCommon';
    
    // Language & Accessibility
    language: string; // Video language code
    audioTrackType: 'original' | 'dubbed' | 'descriptive';
    defaultAudioLanguage?: string;
    captionsCertification: 'none' | 'selfCertified' | 'certified';
    
    // Subtitles/Captions
    subtitles: SubtitleTrack[];
    autoGenerateCaptions: boolean;
    
    // Recording Details
    recordingDate?: string;
    recordingLocation?: VideoLocation;
    
    // Video Type Settings
    isShort: boolean;
    shortsSampling: boolean; // Allow sampling in Shorts
    is360Video: boolean;
    isVRVideo: boolean;
    isHDR: boolean;
    projection?: '360' | 'rectangular';
    stereoLayout?: 'mono' | 'left_right' | 'top_bottom';
    
    // Chapters
    autoChapters: boolean;
    chapters: VideoChapter[];
    
    // End Screen & Cards
    endScreenEnabled: boolean;
    endScreenElements: EndScreenElement[];
    cardsEnabled: boolean;
    cards: VideoCard[];
    
    // Channel Features
    showChannelWatermark: boolean;
    
    // Super Features (Monetization)
    superThanksEnabled: boolean;
    superChatEnabled: boolean;
    superStickerEnabled: boolean;
    membershipPromoEnabled: boolean;
    
    // Sponsorship
    sponsorSegments: SponsorSegment[];
}

export interface SubtitleTrack {
    id: string;
    language: string;
    languageName: string;
    name?: string; // Track name for multiple tracks in same language
    file?: File;
    fileUrl?: string;
    isAutoGenerated: boolean;
    isASR: boolean; // Automatic Speech Recognition
    isCC: boolean; // Closed Captions (includes sound descriptions)
    status: 'draft' | 'published' | 'processing';
}

export interface EndScreenElement {
    id: string;
    type: 'video' | 'playlist' | 'channel' | 'subscribe' | 'link' | 'merchandise';
    position: { x: number; y: number }; // Percentage position
    size: { width: number; height: number };
    startTime: number; // Seconds from end (5-20 seconds before end)
    duration: number; // How long to show (seconds)
    // Type-specific data
    videoId?: string;
    playlistId?: string;
    channelId?: string;
    linkUrl?: string;
    linkTitle?: string;
    merchandiseUrl?: string;
    bestForViewer?: boolean; // Let YouTube choose best video
    mostRecent?: boolean; // Show most recent upload
}

export interface VideoCard {
    id: string;
    type: 'video' | 'playlist' | 'channel' | 'link' | 'donation' | 'poll';
    teaserText: string; // The teaser message (up to 30 chars)
    startTime: number; // When to show (seconds)
    // Type-specific data
    videoId?: string;
    playlistId?: string;
    channelId?: string;
    linkUrl?: string;
    linkTitle?: string;
    customMessage?: string;
    // Poll specific
    pollQuestion?: string;
    pollOptions?: string[];
    // Donation specific
    donationUrl?: string;
    donationSiteName?: string;
}

export interface SponsorSegment {
    id: string;
    type: 'sponsor' | 'intro' | 'outro' | 'self_promo' | 'interaction' | 'music_offtopic' | 'preview' | 'filler';
    startTime: number;
    endTime: number;
    description?: string;
}

export interface VideoLocation {
    description: string;
    latitude?: number;
    longitude?: number;
}

export interface VideoChapter {
    startTime: string; // Format: "00:00"
    title: string;
}

export interface VideoPlaylist {
    id: string;
    title: string;
    thumbnailUrl?: string;
    videoCount: number;
    privacy: 'public' | 'private' | 'unlisted';
}

export interface ScheduledVideo extends YouTubeVideoSettings {
    id: string;
    thumbnailUrl?: string;
    thumbnailFile?: string; // base64
    fileName: string;
    fileSize: number;
    duration?: string;
    status: 'draft' | 'scheduled' | 'uploading' | 'uploaded' | 'failed';
    progress?: number;
    youtubeVideoId?: string;
    createdAt: string;
    updatedAt: string;
    error?: string;
    channelId?: string;
}

export interface VideoDraft extends YouTubeVideoSettings {
    id: string;
    thumbnailUrl?: string;
    createdAt: string;
    updatedAt: string;
}

export interface UploadHistory {
    id: string;
    youtubeVideoId: string;
    title: string;
    thumbnailUrl: string;
    uploadedAt: string;
    scheduledTime?: string;
    publishedAt?: string;
    privacyStatus: string;
    views?: number;
    likes?: number;
    comments?: number;
    channelId?: string;
    channelTitle?: string;
}

export interface YouTubeChannel {
    id: string;
    title: string;
    thumbnailUrl: string;
    subscriberCount: number;
    videoCount: number;
    isConnected: boolean;
    connectedAt?: string;
    // Account info for multi-account support
    accountEmail?: string;
    accountName?: string;
    isBrandAccount?: boolean;
}

// Extended channel info with token data (stored server-side)
export interface ConnectedChannel extends YouTubeChannel {
    accessToken: string;
    refreshToken?: string;
    tokenExpiry?: number;
    connectedAt: string;
    accountEmail: string;
    accountName: string;
    isBrandAccount: boolean;
}

// Multi-channel state
export interface MultiChannelState {
    channels: YouTubeChannel[];
    activeChannelId: string | null;
    // Group channels by account email
    accounts: {
        email: string;
        name: string;
        channels: YouTubeChannel[];
    }[];
}

export interface YouTubeCategory {
    id: string;
    title: string;
}

export interface YouTubeLanguage {
    code: string;
    name: string;
}

// Video Analysis & Scores
export interface AnalyticsPreview {
    estimatedViews: { min: number; max: number };
    estimatedEngagement: number;
    bestTimeRecommendation: string;
    similarVideosPerformance: {
        avgViews: number;
        avgLikes: number;
        avgComments: number;
    };
    titleScore: number;
    descriptionScore: number;
    tagsScore: number;
    overallScore: number;
    hashtagAnalysis?: {
        count: number;
        isOptimal: boolean;
        suggestions: string[];
    };
    seoAnalysis?: {
        keywordDensity: number;
        readabilityScore: number;
        suggestions: string[];
    };
}

export interface AIGeneratedContent {
    titles: string[];
    descriptions: string[];
    tags: string[];
    hashtags: string[];
    chapters?: VideoChapter[];
}

// Default video settings
export const DEFAULT_VIDEO_SETTINGS: Omit<YouTubeVideoSettings, 'title' | 'description'> = {
    tags: [],
    hashtags: [],
    categoryId: '22', // People & Blogs
    playlistIds: [],
    privacyStatus: 'private',
    scheduleTimezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    isPremiere: false,
    premiereCountdownTheme: 'default',
    premiereEnableLiveChat: true,
    premiereLiveRedirectEnabled: false,
    madeForKids: 'no',
    ageRestriction: false,
    hasPaidPromotion: false,
    commentsMode: 'all',
    sortCommentsBy: 'top',
    showRatings: true,
    firstComment: '',
    allowEmbedding: true,
    publishToFeed: true,
    allowSearching: true,
    allowClips: true,
    allowRemix: true,
    allowAITraining: true,
    isAIGenerated: false,
    hasAlteredContent: false,
    license: 'youtube',
    language: 'en',
    audioTrackType: 'original',
    captionsCertification: 'none',
    subtitles: [],
    autoGenerateCaptions: true,
    isShort: false,
    shortsSampling: true,
    is360Video: false,
    isVRVideo: false,
    isHDR: false,
    autoChapters: true,
    chapters: [],
    endScreenEnabled: true,
    endScreenElements: [],
    cardsEnabled: true,
    cards: [],
    showChannelWatermark: true,
    superThanksEnabled: true,
    superChatEnabled: true,
    superStickerEnabled: true,
    membershipPromoEnabled: true,
    sponsorSegments: [],
};

// YouTube's supported languages
export const YOUTUBE_LANGUAGES: YouTubeLanguage[] = [
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Spanish' },
    { code: 'fr', name: 'French' },
    { code: 'de', name: 'German' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'ru', name: 'Russian' },
    { code: 'ja', name: 'Japanese' },
    { code: 'ko', name: 'Korean' },
    { code: 'zh', name: 'Chinese' },
    { code: 'ar', name: 'Arabic' },
    { code: 'hi', name: 'Hindi' },
    { code: 'it', name: 'Italian' },
    { code: 'nl', name: 'Dutch' },
    { code: 'pl', name: 'Polish' },
    { code: 'tr', name: 'Turkish' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'th', name: 'Thai' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ms', name: 'Malay' },
    { code: 'fil', name: 'Filipino' },
];

export interface SchedulerState {
    channels: YouTubeChannel[];
    activeChannelId: string | null;
    drafts: VideoDraft[];
    scheduled: ScheduledVideo[];
    history: UploadHistory[];
    categories: YouTubeCategory[];
    playlists: VideoPlaylist[];
}
